### ISSUE TITLE
Code binary size

### ISSUE THREAD

**Issue by HamzaHajeir** [chronoxor/CppSerialization#5]
Hi 

Yet it's implementation dependent, it's nice to add the binary size of the example, it gives a glance of memory dependency, which is critical for embedded applications.

Best,
Hamza

**Comment by chronoxor** [comment]
Example binaries static linked (contains all dependences)
![image](https://github.com/chronoxor/CppSerialization/assets/4397805/afbbbe07-444a-4a02-95b2-c1cf3699931c)

**Comment by HamzaHajeir** [comment]
I think this is a good information, thanks.
